/**
 * Spec catalogue for every storefront media slot.
 *
 * This is the single source of truth for: expected dimensions, aspect ratios,
 * upload size caps, allowed media kind, and the page grouping used by the
 * WYSIWYG admin to paint overlays on the live iframe.
 *
 * When a new storefront slot is added, register it here AND call the
 * PageSlot upsert in the backfill script — nothing else wires it up.
 */

import { MediaKind } from '@prisma/client';

export interface SlotSpec {
  readonly pageKey: string;
  readonly slotKey: string;
  readonly label: string;
  readonly mediaKind: MediaKind;
  readonly acceptsVideo: boolean;
  readonly specWidth: number;
  readonly specHeight: number;
  readonly specAspect: string;
  readonly maxBytes: number;
  readonly position?: number;
  readonly groupKey?: string;
  readonly defaultHeading?: string;
  readonly defaultSubheading?: string;
  readonly defaultBody?: string;
  readonly defaultCtaLabel?: string;
  readonly defaultCtaHref?: string;
}

const MB = 1024 * 1024;

export const PAGE_KEYS = {
  home: 'home',
  shop: 'shop',
  collectionsIndex: 'collections-index',
  collectionBestsellers: 'collection-bestsellers',
  productDetail: 'product-detail',
  bundlesIndex: 'bundles-index',
  bundleDetail: 'bundle-detail',
  about: 'about',
  career: 'career',
  contact: 'contact',
  returns: 'returns',
  privacy: 'privacy',
  terms: 'terms',
  sizeGuide: 'size-guide',
  nav: 'nav',
  series: 'series',
  trackOrder: 'track-order',
  outlets: 'outlets',
  auth: 'auth',
  notFound: 'not-found',
  search: 'search',
} as const;

export const SLOT_SPECS: readonly SlotSpec[] = [
  // ─── HOME ───────────────────────────────────────────────────────────────────
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'hero_main',
    label: 'Hero (image or video)',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 15 * MB,
    defaultHeading: 'Denim rewritten.',
    defaultCtaLabel: 'Shop now',
    defaultCtaHref: '/shop',
  },

  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'category_card_1',
    label: 'Category card 1',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'home.category_cards',
    position: 0,
    specWidth: 1200,
    specHeight: 1600,
    specAspect: '3:4',
    maxBytes: 2 * MB,
    defaultHeading: 'Wide-Leg',
    defaultCtaHref: '/shop/womens/womens-wide-leg',
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'category_card_2',
    label: 'Category card 2',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'home.category_cards',
    position: 1,
    specWidth: 1200,
    specHeight: 1600,
    specAspect: '3:4',
    maxBytes: 2 * MB,
    defaultHeading: 'Baggy Fit',
    defaultCtaHref: '/shop/womens/womens-baggy',
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'category_card_3',
    label: 'Category card 3',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'home.category_cards',
    position: 2,
    specWidth: 1200,
    specHeight: 1600,
    specAspect: '3:4',
    maxBytes: 2 * MB,
    defaultHeading: 'Cargo',
    defaultCtaHref: '/shop/womens/womens-cargo',
  },

  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'editorial_slide_1',
    label: 'Editorial carousel slide 1',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    groupKey: 'home.editorial',
    position: 0,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 3 * MB,
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'editorial_slide_2',
    label: 'Editorial carousel slide 2',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    groupKey: 'home.editorial',
    position: 1,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 3 * MB,
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'editorial_slide_3',
    label: 'Editorial carousel slide 3',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    groupKey: 'home.editorial',
    position: 2,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 3 * MB,
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'editorial_slide_4',
    label: 'Editorial carousel slide 4',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    groupKey: 'home.editorial',
    position: 3,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 3 * MB,
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'editorial_slide_5',
    label: 'Editorial carousel slide 5',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    groupKey: 'home.editorial',
    position: 4,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 3 * MB,
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'editorial_slide_6',
    label: 'Editorial carousel slide 6',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    groupKey: 'home.editorial',
    position: 5,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 3 * MB,
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'editorial_slide_7',
    label: 'Editorial carousel slide 7',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    groupKey: 'home.editorial',
    position: 6,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 3 * MB,
  },
  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'editorial_slide_8',
    label: 'Editorial carousel slide 8',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    groupKey: 'home.editorial',
    position: 7,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 3 * MB,
  },

  {
    pageKey: PAGE_KEYS.home,
    slotKey: 'brand_story_backdrop',
    label: 'Brand story backdrop',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 4 * MB,
    defaultHeading: 'The Denimisia story.',
    defaultBody: 'Premium denim, built in Bangladesh, for the modern everyday.',
  },

  // ─── COLLECTIONS ────────────────────────────────────────────────────────────
  {
    pageKey: PAGE_KEYS.collectionsIndex,
    slotKey: 'collections_hero',
    label: 'Collections index hero',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 2560,
    specHeight: 1330,
    specAspect: '16:8.3',
    maxBytes: 3 * MB,
    defaultHeading: 'Curated collections.',
  },

  {
    pageKey: PAGE_KEYS.collectionBestsellers,
    slotKey: 'bestsellers_parallax_hero',
    label: 'Bestsellers parallax hero',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 2560,
    specHeight: 1920,
    specAspect: '4:3',
    maxBytes: 4 * MB,
    defaultHeading: 'Bestsellers',
    defaultSubheading: 'Our most-loved silhouettes.',
  },

  // ─── BUNDLES ────────────────────────────────────────────────────────────────
  {
    pageKey: PAGE_KEYS.bundlesIndex,
    slotKey: 'bundles_hero',
    label: 'Bundles hero',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 4 * MB,
    defaultHeading: 'Denim pairs, done for you.',
  },

  // ─── ABOUT ──────────────────────────────────────────────────────────────────
  {
    pageKey: PAGE_KEYS.about,
    slotKey: 'about_hero',
    label: 'About hero',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 2560,
    specHeight: 1330,
    specAspect: '16:8.3',
    maxBytes: 3 * MB,
    defaultHeading: 'Denim with a point of view.',
  },
  {
    pageKey: PAGE_KEYS.about,
    slotKey: 'about_story_image',
    label: 'About story image',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 1600,
    specHeight: 2000,
    specAspect: '4:5',
    maxBytes: 2 * MB,
  },
  {
    pageKey: PAGE_KEYS.about,
    slotKey: 'about_body',
    label: 'About body copy',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 0,
    specHeight: 0,
    specAspect: 'text-only',
    maxBytes: 0,
    defaultBody: '<p>We make denim the old way — with patience.</p>',
  },

  // ─── AUTH ───────────────────────────────────────────────────────────────────
  {
    pageKey: PAGE_KEYS.auth,
    slotKey: 'auth_editorial_panel',
    label: 'Auth side panel image',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 1600,
    specHeight: 2400,
    specAspect: '2:3',
    maxBytes: 3 * MB,
  },

  // ─── MISSING OPPORTUNITY SLOTS (new) ────────────────────────────────────────
  {
    pageKey: PAGE_KEYS.career,
    slotKey: 'career_hero',
    label: 'Career hero',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 2560,
    specHeight: 1440,
    specAspect: '16:9',
    maxBytes: 4 * MB,
    defaultHeading: 'Build with us.',
    defaultSubheading: 'Open roles at Denimisia.',
  },
  {
    pageKey: PAGE_KEYS.career,
    slotKey: 'career_team_1',
    label: 'Team photo 1',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'career.team',
    position: 0,
    specWidth: 1200,
    specHeight: 1500,
    specAspect: '4:5',
    maxBytes: 2 * MB,
  },
  {
    pageKey: PAGE_KEYS.career,
    slotKey: 'career_team_2',
    label: 'Team photo 2',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'career.team',
    position: 1,
    specWidth: 1200,
    specHeight: 1500,
    specAspect: '4:5',
    maxBytes: 2 * MB,
  },
  {
    pageKey: PAGE_KEYS.career,
    slotKey: 'career_team_3',
    label: 'Team photo 3',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'career.team',
    position: 2,
    specWidth: 1200,
    specHeight: 1500,
    specAspect: '4:5',
    maxBytes: 2 * MB,
  },
  {
    pageKey: PAGE_KEYS.career,
    slotKey: 'career_body',
    label: 'Career body copy',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 0,
    specHeight: 0,
    specAspect: 'text-only',
    maxBytes: 0,
    defaultBody: '<p>We are hiring across design, ops, and engineering.</p>',
  },

  {
    pageKey: PAGE_KEYS.contact,
    slotKey: 'contact_hero',
    label: 'Contact hero',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 2560,
    specHeight: 1330,
    specAspect: '16:8.3',
    maxBytes: 3 * MB,
    defaultHeading: 'Talk to us.',
  },
  {
    pageKey: PAGE_KEYS.contact,
    slotKey: 'contact_side',
    label: 'Contact form side image',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 1200,
    specHeight: 1500,
    specAspect: '4:5',
    maxBytes: 2 * MB,
  },

  {
    pageKey: PAGE_KEYS.returns,
    slotKey: 'returns_hero',
    label: 'Returns hero',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 2560,
    specHeight: 1330,
    specAspect: '16:8.3',
    maxBytes: 3 * MB,
    defaultHeading: 'Returns & exchanges.',
  },
  {
    pageKey: PAGE_KEYS.returns,
    slotKey: 'returns_body',
    label: 'Returns policy body',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 0,
    specHeight: 0,
    specAspect: 'text-only',
    maxBytes: 0,
    defaultBody: '<p>14-day returns on full-price items.</p>',
  },

  {
    pageKey: PAGE_KEYS.privacy,
    slotKey: 'privacy_hero',
    label: 'Privacy hero',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 2560,
    specHeight: 1330,
    specAspect: '16:8.3',
    maxBytes: 3 * MB,
    defaultHeading: 'Privacy policy.',
  },

  {
    pageKey: PAGE_KEYS.terms,
    slotKey: 'terms_hero',
    label: 'Terms of service hero',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 2560,
    specHeight: 1330,
    specAspect: '16:8.3',
    maxBytes: 3 * MB,
    defaultHeading: 'Terms of service.',
  },
  {
    pageKey: PAGE_KEYS.privacy,
    slotKey: 'privacy_body',
    label: 'Privacy body',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 0,
    specHeight: 0,
    specAspect: 'text-only',
    maxBytes: 0,
    defaultBody: '<p>How we handle your data.</p>',
  },

  {
    pageKey: PAGE_KEYS.sizeGuide,
    slotKey: 'size_guide_chart_wide_leg',
    label: 'Wide-leg size chart',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'sizeGuide.charts',
    position: 0,
    specWidth: 1600,
    specHeight: 2000,
    specAspect: '4:5',
    maxBytes: 2 * MB,
  },
  {
    pageKey: PAGE_KEYS.sizeGuide,
    slotKey: 'size_guide_chart_baggy',
    label: 'Baggy size chart',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'sizeGuide.charts',
    position: 1,
    specWidth: 1600,
    specHeight: 2000,
    specAspect: '4:5',
    maxBytes: 2 * MB,
  },
  {
    pageKey: PAGE_KEYS.sizeGuide,
    slotKey: 'size_guide_chart_cargo',
    label: 'Cargo size chart',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'sizeGuide.charts',
    position: 2,
    specWidth: 1600,
    specHeight: 2000,
    specAspect: '4:5',
    maxBytes: 2 * MB,
  },

  {
    pageKey: PAGE_KEYS.trackOrder,
    slotKey: 'track_order_hero',
    label: 'Track order hero',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 2560,
    specHeight: 1330,
    specAspect: '16:8.3',
    maxBytes: 3 * MB,
    defaultHeading: 'Track your order.',
  },

  {
    pageKey: PAGE_KEYS.outlets,
    slotKey: 'outlet_card_1',
    label: 'Outlet card 1',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'outlets.cards',
    position: 0,
    specWidth: 1600,
    specHeight: 1000,
    specAspect: '16:10',
    maxBytes: 2 * MB,
  },
  {
    pageKey: PAGE_KEYS.outlets,
    slotKey: 'outlet_card_2',
    label: 'Outlet card 2',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    groupKey: 'outlets.cards',
    position: 1,
    specWidth: 1600,
    specHeight: 1000,
    specAspect: '16:10',
    maxBytes: 2 * MB,
  },

  {
    pageKey: PAGE_KEYS.notFound,
    slotKey: 'not_found_illustration',
    label: '404 illustration',
    mediaKind: 'IMAGE',
    acceptsVideo: true,
    specWidth: 1600,
    specHeight: 1200,
    specAspect: '4:3',
    maxBytes: 3 * MB,
    defaultHeading: 'Lost in the fabric.',
    defaultSubheading: "The page you're looking for has moved on.",
  },

  {
    pageKey: PAGE_KEYS.search,
    slotKey: 'search_empty_illustration',
    label: 'Empty search illustration',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 1600,
    specHeight: 1200,
    specAspect: '4:3',
    maxBytes: 2 * MB,
    defaultHeading: 'No matches.',
    defaultSubheading: 'Try fewer keywords or browse the shop.',
  },

  // ─── SEARCH ── Popular-category tiles rendered inside the search overlay ───
  // The 3 fixed tiles below the search box. Customer clicks a tile to jump
  // into the corresponding collection page.
  {
    pageKey: PAGE_KEYS.search,
    slotKey: 'category_denims',
    label: 'Search · Denims tile',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: 1,
    groupKey: 'search.popular_categories',
  },
  {
    pageKey: PAGE_KEYS.search,
    slotKey: 'category_tops',
    label: 'Search · Tops tile',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: 2,
    groupKey: 'search.popular_categories',
  },
  {
    pageKey: PAGE_KEYS.search,
    slotKey: 'category_jackets',
    label: 'Search · Jackets tile',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: 3,
    groupKey: 'search.popular_categories',
  },

  // ─── NAV ── Mega-menu featured images (visible on every storefront page) ───
  {
    pageKey: PAGE_KEYS.nav,
    slotKey: 'featured_shop_women',
    label: 'Mega-menu · Shop / Women',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: 1,
    groupKey: 'nav.featured',
  },
  {
    pageKey: PAGE_KEYS.nav,
    slotKey: 'featured_shop_men',
    label: 'Mega-menu · Shop / Men',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: 2,
    groupKey: 'nav.featured',
  },
  {
    pageKey: PAGE_KEYS.nav,
    slotKey: 'featured_collection_latest',
    label: 'Mega-menu · Collection / Latest',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: 3,
    groupKey: 'nav.featured',
  },
  {
    pageKey: PAGE_KEYS.nav,
    slotKey: 'featured_series_bestsellers',
    label: 'Mega-menu · Series / Best sellers',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: 4,
    groupKey: 'nav.featured',
  },
  {
    pageKey: PAGE_KEYS.nav,
    slotKey: 'featured_series_wide_leg',
    label: 'Mega-menu · Series / Wide leg',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: 5,
    groupKey: 'nav.featured',
  },

  // ─── SERIES ── Top-level type heroes (tops + pants landing pages) ──────────
  {
    pageKey: PAGE_KEYS.series,
    slotKey: 'hero_tops',
    label: 'Series · Tops hero',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 2560,
    specHeight: 1024,
    specAspect: '16:6.4',
    maxBytes: 3 * MB,
    defaultHeading: 'Tops.',
  },
  {
    pageKey: PAGE_KEYS.series,
    slotKey: 'hero_pants',
    label: 'Series · Pants hero',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 2560,
    specHeight: 1024,
    specAspect: '16:6.4',
    maxBytes: 3 * MB,
    defaultHeading: 'Pants.',
  },

  // ─── SHOP ── Gender landing hero (rendered at the top of /shop/women + men) ─
  {
    pageKey: PAGE_KEYS.shop,
    slotKey: 'hero_women',
    label: 'Shop Women hero',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 2560,
    specHeight: 1180,
    specAspect: '16:7.4',
    maxBytes: 3 * MB,
    defaultHeading: 'Shop Women.',
  },
  {
    pageKey: PAGE_KEYS.shop,
    slotKey: 'hero_men',
    label: 'Shop Men hero',
    mediaKind: 'IMAGE',
    acceptsVideo: false,
    specWidth: 2560,
    specHeight: 1180,
    specAspect: '16:7.4',
    maxBytes: 3 * MB,
    defaultHeading: 'Shop Men.',
  },

  // ─── SHOP ── Fit-carousel tiles (Shop by Fit on the shop landing) ──────────
  // 11 individually-uploadable tiles, one per fit slug. Tile label + link
  // are taxonomy and stay in storefront source; only the image is admin-
  // controlled here. Add a new tile by registering a slot and exposing
  // the corresponding link target in apps/web/components/shop/fit-carousel.tsx.
  ...(
    [
      { slug: 'cargo', label: 'Cargo' },
      { slug: 'culotte', label: 'Culotte' },
      { slug: 'flare', label: 'Flare' },
      { slug: 'wide-leg', label: 'Wide Leg' },
      { slug: 'mom', label: 'Mom' },
      { slug: 'jegging', label: 'Jegging' },
      { slug: 'slouchy', label: 'Slouchy' },
      { slug: 'skinny', label: 'Skinny' },
      { slug: 'straight', label: 'Straight' },
      { slug: 'sweatshirt', label: 'Sweatshirt' },
      { slug: 'jacket', label: 'Jacket' },
    ] as const
  ).map((fit, index) => ({
    pageKey: PAGE_KEYS.shop,
    slotKey: `fit_${fit.slug.replace(/-/g, '_')}`,
    label: `Fit tile · ${fit.label}`,
    mediaKind: 'IMAGE' as const,
    acceptsVideo: false,
    specWidth: 900,
    specHeight: 1125,
    specAspect: '4:5',
    maxBytes: 2 * MB,
    position: index + 1,
    groupKey: 'shop.fits',
  })),
];

export function findSpec(
  pageKey: string,
  slotKey: string,
): SlotSpec | undefined {
  return SLOT_SPECS.find((s) => s.pageKey === pageKey && s.slotKey === slotKey);
}
